
#if CONFIG_ESP32_C6_WROOM_1
    #define GPIO_PRESENCE_SENSOR GPIO_NUM_0
    #define GPIO_VBUS_CC2        GPIO_NUM_1
    #define GPIO_VBUS_CC1        GPIO_NUM_2
    #define GPIO_UART_RX         GPIO_NUM_6
    #define GPIO_UART_TX         GPIO_NUM_7
    #define GPIO_PSU_EN          GPIO_NUM_11
    #define GPIO_RCLK            GPIO_NUM_18
    #define GPIO_SRDATA          GPIO_NUM_19
    #define GPIO_SRCLK           GPIO_NUM_20
    #define GPIO_OUTPUT_EN       GPIO_NUM_21
#elif CONFIG_ESP32_C6_MINI_1
    #define GPIO_PRESENCE_SENSOR GPIO_NUM_0
    //#define GPIO_VBUS_CC2        GPIO_NUM_
    //#define GPIO_VBUS_CC1        GPIO_NUM_
    #define GPIO_UART_RX         GPIO_NUM_4
    #define GPIO_UART_TX         GPIO_NUM_5
    #define GPIO_PSU_EN          GPIO_NUM_7
    #define GPIO_RCLK            GPIO_NUM_15
    #define GPIO_SRDATA          GPIO_NUM_18
    #define GPIO_SRCLK           GPIO_NUM_19
    #define GPIO_OUTPUT_EN       GPIO_NUM_20
#endif

#define RMT_RESOLUTION_HZ 1000000 // 1MHZ, 1 tick = 1us

#define PWM_RESOLUTION_BITS 10    // PWM duty-cycle resolution is 0-1024

#define ENABLE  1
#define DISABLE 0

#define ESP_INTR_FLAG_DEFAULT 0

#define WIFI_CONNECTED_BIT BIT0
#define WIFI_FAIL_BIT      BIT1

#define TIMER_UPDATE_DISP 1
#define TIMER_ROLL_DISP   2
#define TIMER_NO_MOVEMENT 3

#define WIFI_SUCCESS 1
#define WIFI_FAILURE 2

#define MAIN_TASK_SETUP_DONE 1
#define ANIMATION_TASK_DONE  2

#define ESP_WIFI_SSID           CONFIG_ESP_WIFI_SSID
#define ESP_WIFI_PASS           CONFIG_ESP_WIFI_PASSWORD
#define ESP_MAXIMUM_RETRY       CONFIG_ESP_MAXIMUM_RETRY

#define SNTP_TIME_SERVER        CONFIG_SNTP_TIME_SERVER

#if CONFIG_ESP_WIFI_AUTH_OPEN
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_OPEN
#elif CONFIG_ESP_WIFI_AUTH_WEP
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WEP
#elif CONFIG_ESP_WIFI_AUTH_WPA_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA2_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA_WPA2_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_WPA2_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA3_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA3_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA2_WPA3_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_WPA3_PSK
#elif CONFIG_ESP_WIFI_AUTH_WAPI_PSK
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WAPI_PSK
#endif

#if CONFIG_ESP_WPA3_SAE_PWE_HUNT_AND_PECK
#define ESP_WIFI_SAE_MODE WPA3_SAE_PWE_HUNT_AND_PECK
#define H2E_IDENTIFIER ""
#elif CONFIG_ESP_WPA3_SAE_PWE_HASH_TO_ELEMENT
#define ESP_WIFI_SAE_MODE WPA3_SAE_PWE_HASH_TO_ELEMENT
#define H2E_IDENTIFIER CONFIG_ESP_WIFI_PW_ID
#elif CONFIG_ESP_WPA3_SAE_PWE_BOTH
#define ESP_WIFI_SAE_MODE WPA3_SAE_PWE_BOTH
#define H2E_IDENTIFIER CONFIG_ESP_WIFI_PW_ID
#endif

#if CONFIG_BUILD_MAIN_PROGRAM
#define BUILD_MAIN_PROGRAM
#endif